spring:
  profiles:
    active: dev

###指定SpringBoot监控中心的服务端地址
  boot:
    admin:
      client:
        url: http://localhost:8085

###通过下面的配置启用所有的监控端点，默认情况下，这些端点是禁用的；
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
#多数据源的情况里 xml文件与mapper的关联放在了数据源创建的配置类里面了 这块就不需要配置了
mybatis:
 typeAliasesPackage: com.springbootstudy.demo.entity
 mapperLocations: classpath:mapperXml/**/*.xml
