spring:
  profiles:
    active: dev
# activemq 配置
  activemq:
    broker-url: tcp://localhost:61626
    password: admin
    pool:
      max-connections: 50
      enabled: false #关闭连接池
    user: admin
  # 使用发布/订阅模式时，下边配置需要设置成 true   消费者并没有消费订阅发布类型的消息，这是由于springboot默认采用的是p2p模式进行消息的监听
  jms:
    pub-sub-domain: true

###指定SpringBoot监控中心的服务端地址
  boot:
    admin:
      client:
        url: http://localhost:8085

###通过下面的配置启用所有的监控端点，默认情况下，这些端点是禁用的；
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
#多数据源的情况里 xml文件与mapper的关联放在了数据源创建的配置类里面了 这块就不需要配置了
mybatis:
 typeAliasesPackage: com.springbootstudy.demo.entity
 mapperLocations: classpath:mapperXml/**/*.xml
